services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    entrypoint: ./utils/app-entrypoint.sh
    command: make start_app
  db:
    image: postgres:14.2-alpine3.15
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.10.1-alpine
volumes:
  db:
    driver: local
