services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
      - rabbitmq
      - worker
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    entrypoint: ./utils/app-entrypoint.sh
    command: uvicorn app.api:app --reload --host 0.0.0.0
  worker:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    environment:
      - ENV_TYPE=production
    volumes:
      - .:/code
    entrypoint: ./utils/app-entrypoint.sh
    command: celery -A app.tasks worker --loglevel=INFO
  db:
    image: postgres:14.2-alpine3.15
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.10.1-alpine
volumes:
  db:
    driver: local
