"""create reaction table

Revision ID: 19d985747cb1
Revises: fa7f1a43582b
Create Date: 2022-05-07 14:55:13.299107

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "19d985747cb1"
down_revision = "fa7f1a43582b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reaction",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("training_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "reaction_type",
            sa.Enum("like", "dislike", name="reactiontypeenum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["training.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reaction")
    # ### end Alembic commands ###
